### ISSUE TITLE
Is it possible to have an array search param with multiple defaults

### ISSUE THREAD

**Issue by mikedidthis** [fenok/react-router-typesafe-routes#47]
👋 

Firstly thank you for the amazing library! I am trying to replicate the `ArrayParam` behaviour from [use-query-params](https://www.npmjs.com/package/use-query-params).

```
?qp=one&qp=two
```

If `qp` is missing I want to set the default values to `['one', 'two']`. However it looks like `default()` only expects a string (unless I am missing something?).

**Comment by fenok** [comment]
Hello and thank you!

`array()` is a terminating modifier that ensures the parsed value will be an array (and `default()` only affects the items of this array). As of now, there is no way to specify a default value in this case (in a way, it's implicitly set to `[]`).

You can build a custom type to get the behavior you want:

```typescript
const stringArray = (def: string[]): SearchParamType<string[]> => ({
    getPlainSearchParam(value) {
        // No need to check for undefined, and values are escaped automatically
        return value;
    },
    getTypedSearchParam(value) {
        // Values are automatically unescaped, and empty array means that there is no such param
        return value.length ? value : def;
    },
});

const MyRoute = route("", { searchParams: { qp: stringArray(["one", "two"]) } });
```

I hope this helps.

**Comment by mikedidthis** [comment]
Perfect! Works as expected thanks for the quick response.
