### ISSUE TITLE
1.2.2 - How to access fragment param values?

### ISSUE THREAD

**Issue by edward-simpson** [fenok/react-router-typesafe-routes#57]
In the v1 examples, the fragments are all search parameters.

When using fragments for reusable params, the value always seems to be undefined, e.g.

```ts
const ID_FRAGMENT = route('', { params: { id: string() } })

const ExampleRoute = route('test-route/:id', types(ID_FRAGMENT))

// ... inside router
<Route path={ExampleRoute.path} element={<TestElement />} />

const TestElement = () => {
    const { id } = useTypedParams(ExampleRoute)
    // id is always undefined, even when an id is provided
}
```

This makes it very hard/impossible to have reusable elements, for routes which share url structure and functionality.

Is there something I'm missing?  From the looks of the doc this is potentially fixed in 2.x.x due to a change in declaring fragments, but this is causing issues now so I can't wait for v2!

**Comment by fenok** [comment]
Sorry for the late response.

Pathname params are determined by the path pattern. Their types can be overridden, but you can't add params without mentioning them in the pattern.

In other words, ID_FRAGMENT should be defined like this:

```
const ID_FRAGMENT = route(':id', { params: { id: string() } })
```

Which is admittedly confusing (this fragment will never be used to build a path, why does it even require a pattern?).

This is solved in v2 by:
- Raising a TS error when there's an attempt to override a non-existing pathname param.
- Introducing pathless routes, where you can indeed define pathname params (for parsing only) just by specifying their types.

**Comment by edward-simpson** [comment]
Fantastic!
