### ISSUE TITLE
Compatibility with React Router v7

### ISSUE THREAD

**Issue by rothsandro** [fenok/react-router-typesafe-routes#58]
Hi 👋 React Router v7 was released today. Will you update the library to be compatible with the new version?

**Comment by fenok** [comment]
Hi! Yes, at first glance it looks easy. However, it'll likely be a part of the 2.0 release.

**Comment by fenok** [comment]
I updated the library for React Router v7 and released it just now.

**Comment by rothsandro** [comment]
Yeah, thanks a lot 🙏
